Html nri
ryuichi-58/Ryuichi_Kamei pull request #1
Opened 2020-10-22 14:56 UTC by ryuichi-58

課題①のhtmlコーディングが完了しました。
#html-nri

2020-10-24 04:04 UTC, n06Ar requested changes
口頭でお話したものも含めて追加でコメントをしました。
ご確認をお願いいたします。

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +        <link rel="icon" type="image/png" href="image/favicon.png">
ogpタグがないので追加をお願いします。

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +                    <img src="image/main_visual.jpg" alt="高層ビル郡">
ここの画像は文書的な意味より装飾の意味合いが近いのでalt属性の中身を消し`aria-hidden="true"`をつけてください

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +        <div class="breadcrumb" >
パンくずリストもナビゲーションに含まれるので、navタグにした方が良さそうです。

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +            <ol>
ここはパンくずリストなので、ulでよいです。

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +                    <figure></figure>
画像を忘れずに入れておいてください

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +                <p class="sub_title">経営方針</p>
`.sub_title`は、全体的に見出しと解釈できるのでh系のタグを使用してください。

2020-10-24 04:04 UTC, n06Ar commented on nri.html
> +                      <li><a href="#" class="subject">ナレッジ・インサイト</a></li>
ここも見出しの意味合いとして解釈できるので、ulタグと同じ階層におき、h系のタグを使うと良いです。

2020-10-26 05:26 UTC, ryuichi-58 commented
html初回提出のレビュー指摘箇所を修正しました。
CSSもコーディングできましたので、大変お忙しいとは存じますが
ご査収のほど宜しくお願い致します。

2020-10-26 05:41 UTC, merged